/* Version information autogenerated by version fragment */
#ifndef BOMKI_analysis_NAME
#define BOMKI_analysis_NAME "BOMKI_analysis"
#define BOMKI_analysis_VERSION "v999"
#define BOMKI_analysis_MAJOR_VERSION 999
#define BOMKI_analysis_MINOR_VERSION 0
#define BOMKI_analysis_PATCH_VERSION 0
#define BEFORE_BOMKI_analysis(v,r,p) ((BOMKI_analysis_MAJOR_VERSION==(v)&&BOMKI_analysis_MINOR_VERSION==(r)&&BOMKI_analysis_PATCH_VERSION<(p))||(BOMKI_analysis_MAJOR_VERSION==(v)&&BOMKI_analysis_MINOR_VERSION<(r))||(BOMKI_analysis_MAJOR_VERSION<(v)))
#define EQUALS_BOMKI_analysis(v,r,p) (BOMKI_analysis_MAJOR_VERSION==(v)&&BOMKI_analysis_MINOR_VERSION==(r)&&BOMKI_analysis_PATCH_VERSION==(p))
#define BOMKI_analysis_COMPILE_DATE "Sat Apr 29 15:31:46 UTC 2017"
#define BOMKI_analysis_COMPILE_HOST "localhost.localdomain"
#define BOMKI_analysis_COMPILE_UNAME "Linux localhost.localdomain 3.10.0-514.6.1.el7.x86_64 #1 SMP Tue Jan 17 11:12:41 CST 2017 x86_64 x86_64 x86_64 GNU/Linux"
#define BOMKI_analysis_COMPILE_DIR "/home/bomki/ICEDUST/BOMKI_analysis/v999/cmt"
#endif
